repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
        exclude: |
          (?x)(
            ^.*build/|
            ^.*md|
            .yarn/*|
            yarn-patches
          )
      - id: check-yaml
      - id: check-added-large-files
        args: ["--maxkb=10000"]
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/prettier/pre-commit
    rev: "57f39166b5a5a504d6808b87ab98d41ebf095b46"
    hooks:
      - id: prettier
        files: "\\.(\
          css\
          |html\
          |js|jsx\
          |json\
          |ts|tsx\
          |yaml|yml\
          )$"
